Activation Layers



In [6]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x= tf.random.normal(shape=(1,5)) #input

# imp. activation function

sigmoid = Activation('sigmoid') # activation을 sigmoid function으로 만듬
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)


print("x : {}\n{}".format(x.shape, x.numpy()))
print("sigmoid(tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("tanh(tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("relu(tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))


# forward propagation(manual)
y_sigmoid_man = 1/ (1+exp(-x))
y_tanh_man = (exp(x)-exp(-x))/(exp(x)+exp(-x))
y_relu_man = maximum(x,0)

print("x : {}\n{}".format(x.shape, x.numpy()))
print("sigmoid(manual): {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))
print("tanh(manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))
print("relu(manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x : (1, 5)
[[-2.7298937   0.15390831  0.2791101   1.1570961  -0.33311635]]
sigmoid(tensorflow): (1, 5)
[[0.06123224 0.5384013  0.569328   0.76080465 0.41748255]]
tanh(tensorflow): (1, 5)
[[-0.9915272   0.15270446  0.27208126  0.82009125 -0.32131818]]
relu(tensorflow): (1, 5)
[[0.         0.15390831 0.2791101  1.1570961  0.        ]]
x : (1, 5)
[[-2.7298937   0.15390831  0.2791101   1.1570961  -0.33311635]]
sigmoid(manual): (1, 5)
[[0.06123227 0.5384013  0.569328   0.76080465 0.41748255]]
tanh(manual): (1, 5)
[[-0.9915271   0.15270448  0.27208126  0.8200913  -0.3213182 ]]
relu(manual): (1, 5)
[[0.         0.15390831 0.2791101  1.1570961  0.        ]]


Activation in Dense Layer

In [10]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x= tf.random.normal(shape=(1,5)) #input

# imp. artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid') # affine function을 만들고 그 뒤에 바로 activation function이 들어오는것과 같다.
# 즉, dense layer의 기능은 affine function과 activation function을 같이 만드는 기능을 한다.
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation
y_sigmoid =dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with relu: {}\n{}".format(y_relu.shape, y_relu.numpy())) 
# numpy로 출력하는건 행렬형태이기 때문에 보기 편하라고 numpy로 출력
'''
결과에서 shape이 (1,1)인 이유는, input행렬이 (1,5)이니까 weight은 (5,1)이 될것이고
따라서 행렬 곱하기 계산하면 1개의 값만 도출된다.
'''

# forward propagation(manual)
print('\n==========\n')
from tensorflow.math import exp

W, b = dense_sigmoid.get_weights()
z= tf.linalg.matmul(x,W)+b # affine function 직접 계산
a = 1/(1+exp(-z)) # sigmoid의 activation function 계산
print('Activation value(Tensorflow):{}\n{}'.format(y_sigmoid.shape,y_sigmoid.numpy()))
print('Activation value(manual):{}\n{}'.format(a.shape,a.numpy()))

AN with sigmoid: (1, 1)
[[0.3289156]]
AN with tanh: (1, 1)
[[-0.2029668]]
AN with relu: (1, 1)
[[0.]]


Activation value(Tensorflow):(1, 1)
[[0.3289156]]
Activation value(manual):(1, 1)
[[0.3289156]]


Artificial Neurons

In [15]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid' # tanh, relu 이여도 가능

x= tf.random.uniform(shape=(1,10)) #input

dense=Dense(units=1, activation= activation)
y_tf = dense(x)
W, B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) +B
if activation == 'sigmoid':
  y_man = 1/(1+exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man)-exp(-y_man))/(exp(y_man)+exp(-y_man))
elif activation == 'relu':
  y_man = maximum(y_man,0)

print("Activation : ",activation)
print("y_tf:{}\n{}".format(y_tf.shape,y_tf.numpy()))
print("y_man:{}\n{}".format(y_man.shape,y_man.numpy()))


Activation :  sigmoid
y_tf:(1, 1)
[[0.50862706]]
y_man:(1, 1)
[[0.50862706]]


Shape of Dense Layers

In [19]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature =8,10 # set input params
x= tf.random.normal(shape=(N,n_feature)) # generate minibatch
#print(x.numpy())

dense = Dense(units = 1, activation='relu') # imp.
y= dense(x)

W,B = dense.get_weights()

# forward propagation
print("shape of x: {}".format(x.shape)) # 8,10
print("shape of W: {}".format(W.shape)) # 10,1
print("shape of B: {}".format(B.shape)) # bias는 1개

[[ 0.30607805  1.6772068  -2.6307924   0.20952465  0.04917399 -0.3303821
  -0.81923145 -0.2614152   0.55739146 -0.50637937]
 [ 2.0028076   0.42381418  0.8122073  -0.13107726  2.551365   -0.20515145
   1.4750204   1.3615882  -0.50693053 -1.4458563 ]
 [ 0.74342763 -0.65869564 -0.31595582 -0.9145395   1.5734409  -1.2828509
   0.50607204  0.63092965 -0.39175978 -0.652068  ]
 [-1.6127286  -0.02036365  0.78009623  0.10776231  1.168564    0.34379035
  -0.76747066 -0.17849961 -1.1429365   0.14772984]
 [ 0.133406   -1.1381344   1.5330261   1.1800193   0.8581808  -0.5154972
  -1.4283302   0.76151985  0.34874728 -0.88398176]
 [-1.6066247   1.5478613   0.5640773   0.27829385  0.731845   -0.23915376
   1.6249925   0.33873317  0.3418506  -0.99893004]
 [ 0.20091313  1.8056571   0.06696624 -0.38564467 -0.4099732  -0.3566699
  -1.3614745   0.28168324  0.11816796  0.04612102]
 [-0.3407468   1.183966    1.0963446   0.17989278 -1.2252342  -0.16337956
   0.99739516  1.5558171   0.5745893  -1.5108483 ]]
sha

Output Calculations

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature =8,10 # set input params
x= tf.random.normal(shape=(N,n_feature)) # generate minibatch

dense = Dense(units = 1, activation='sigmoid') # imp.
y_tf = dense(x)

# forward propagation(Tensorflow)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) +B
y_man = 1/(1+exp(-y_man))
# result
print("output(Tensowrflow): \n",y_tf.numpy())
print("output(manual): \n",y_man.numpy())
print(tf.math.equal(y_tf,y_man)) # 같은지 확인
# 그런데 floating point가 달라서 false도 생기긴 함

output(Tensowrflow): 
 [[0.26716083]
 [0.713917  ]
 [0.12341836]
 [0.82812834]
 [0.5599243 ]
 [0.3719393 ]
 [0.23166722]
 [0.82866704]]
output(manual): 
 [[0.26716083]
 [0.713917  ]
 [0.12341838]
 [0.82812834]
 [0.5599243 ]
 [0.37193927]
 [0.23166719]
 [0.82866704]]
