IO of Softmax

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Activation

logits = tf.random.uniform(shape=(2,5),minval=-10,maxval=10)
print(logits)

softmax_value = Activation('softmax')(logits)
softmax_sum = tf.reduce_sum(softmax_value, axis=1) # axis =1 은 행을 축으로 더하라는 뜻

print("Logits: \n",logits.numpy())
print("Probabilities: \n",softmax_value.numpy()) # probablity는 이전의 형태에서 바뀌지는 않는다
print("Sum of softmax values: \n",softmax_sum) # 각 벡터의 합은 확률이기 때문에 1 이여야 하다


tf.Tensor(
[[-2.002902  -6.7173576  1.4510269  9.018101   5.8508663]
 [ 9.482376   5.0342846  2.2246857 -2.3976374 -9.025068 ]], shape=(2, 5), dtype=float32)
Logits: 
 [[-2.002902  -6.7173576  1.4510269  9.018101   5.8508663]
 [ 9.482376   5.0342846  2.2246857 -2.3976374 -9.025068 ]]
Probabilities: 
 [[1.5685531e-05 1.4061681e-07 4.9604557e-04 9.5909125e-01 4.0396851e-02]
 [9.8773962e-01 1.1557420e-02 6.9609354e-04 6.8425534e-06 9.0565226e-09]]
Sum of softmax values: 
 tf.Tensor([1. 1.], shape=(2,), dtype=float32)


Softmax in Dense Layers

In [5]:
import tensorflow as tf
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
dense = Dense(units=8, activation='softmax') # 클래스의 개수만큼 뉴런이 있어야 한다

Y = dense(logit)
print(tf.reduce_sum(Y,axis=1))


tf.Tensor(
[1.        1.        1.        0.9999999 1.        1.0000001 1.
 1.       ], shape=(8,), dtype=float32)


Multi-class Classifiers

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

class TestModel(Model):
  def __init__(self):
    super(TestModel,self).__init__()

    self.dense1 = Dense(units=8,activation='relu')
    self.dense2 = Dense(units=5,activation='relu')
    self.dense3 = Dense(units=3,activation='softmax') 
  
  def call(self,x):
    print("X : {}\n{}\n".format(x.shape,x.numpy()))

    x= self.dense1(x)
    print("A1 : {}\n{}\n".format(x.shape,x.numpy()))

    x= self.dense2(x)
    print("A2 : {}\n{}\n".format(x.shape,x.numpy()))

    x= self.dense3(x)
    print("Y : {}\n{}\n".format(x.shape,x.numpy()))
    print("Sum of Vectors:{} \n".format(tf.reduce_sum(x,axis=1)))
    return x

model = TestModel()

X = tf.random.uniform(shape=(8,5),minval=-10,maxval=10)
Y=model(X)


X : (8, 5)
[[ 9.9858055  -9.429102    3.0639696   8.048315   -2.8625512 ]
 [ 8.432762   -5.393703   -1.2818432   7.24325    -7.4714637 ]
 [ 6.401289    3.1712513   1.2216396   0.08388329  2.2804432 ]
 [-9.970676   -1.2701702  -0.9831829  -5.993998   -9.349148  ]
 [ 7.8338814  -4.087887    4.2086105   0.36858082  4.279666  ]
 [-5.8011317  -9.76021    -5.786388    0.0130825  -1.6786671 ]
 [ 3.3421345   5.899601    5.292404    0.04031944 -0.49292564]
 [ 6.8085747  -4.0652204   2.1391726  -1.149149    5.467041  ]]

A1 : (8, 8)
[[0.0000000e+00 7.0953517e+00 1.0520821e+01 6.0323632e-01 6.9365627e-03
  7.9504142e+00 4.8975878e+00 0.0000000e+00]
 [0.0000000e+00 5.7533894e+00 1.2549304e+01 0.0000000e+00 0.0000000e+00
  1.1451676e+01 5.9319377e+00 0.0000000e+00]
 [1.3306445e+00 3.3505120e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.8993272e+00 0.0000000e+00 7.5428504e-01]
 [0.0000000e+00 0.0000000e+00 3.5380592e+00 0.0000000e+00 8.9586535e+00
  0.0000000e+00 3.9058917e+00 3.9371786e+00]
 [0