SCCE Calculation

In [4]:
import tensorflow as tf
from tensorflow.keras.losses import SparseCategoricalCrossentropy

batch_size, n_class = 16,5

predictions = tf.random.uniform(shape=(batch_size,n_class), minval=0, maxval=1, dtype=tf.float32)
# 확률, 마지막 layer의 뉴런의 개수는 class의 개수와 같아야 한다.

pred_sum = tf.reshape(tf.reduce_sum(predictions,axis=1),(-1,1))
predictions = predictions / pred_sum

labels = tf.random.uniform(shape=(batch_size,),minval=0, maxval=n_class,dtype=tf.int32)

print(labels)  # 이런 식으로 one hot이 아닌 값으로 나올 때는 SparseCategoricalCrossentropy 사용

loss_object = SparseCategoricalCrossentropy()

loss = loss_object(labels, predictions)


print("SparseCategorical(Tensorflow): ",loss.numpy())

ce = 0
for label,prediction in zip(labels,predictions):
  ce += -tf.math.log(prediction[label])

ce/= batch_size # 평균
print("SparseCategorical(Manual): ",ce.numpy())

tf.Tensor([2 2 4 0 0 2 3 3 1 2 0 4 1 4 3 4], shape=(16,), dtype=int32)
SparseCategorical(Tensorflow):  1.9389151
SparseCategorical(Manual):  1.938915


SCCE with Model/Dataset

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy

N,n_feature = 100,2
n_class = 5

X = tf.zeros(shape = (0,n_feature))
Y = tf.zeros(shape=(0,1),dtype = tf.int32)

for class_idx in range(n_class):
  center = tf.random.uniform(minval =-15, maxval=15, shape=(2,)) 

  x1 = center[0] + tf.random.normal(shape=(N,1)) 
  x2 = center[1] + tf.random.normal(shape=(N,1)) 

  x = tf.concat((x1,x2),axis=1)
  y = class_idx*tf.ones(shape=(N,1), dtype=tf.int32)

  X = tf.concat((X,x), axis = 0)
  Y = tf.concat((Y,y), axis = 0)

dataset = tf.data.Dataset.from_tensor_slices((X,Y))
dataset = dataset.batch(batch_size)

model = Dense(units=n_class, activation='softmax')
loss_object = SparseCategoricalCrossentropy()

for x,y in dataset:
  predictions = model(x)
  loss = loss_object(y,predictions)
  print(loss.numpy())

10.047882
9.844177
9.869303
10.027891
10.192861
9.889158
8.303173
7.807233
8.299297
8.09896
8.248482
8.219882
6.4288464
4.9762487
4.923832
4.835242
4.928394
4.8059626
4.322302
1.5966445
1.5629181
1.5330673
1.6117269
1.4243939
1.7527716
3.5662096
3.5664556
3.5032656
3.5450354
3.4359581
3.3738055
3.3985813


CCE Calculation

In [9]:
import tensorflow as tf
from tensorflow.keras.losses import CategoricalCrossentropy

batch_size, n_class = 16,5

predictions = tf.random.uniform(shape=(batch_size,n_class), minval=0, maxval=1, dtype=tf.float32)
# 확률, 마지막 layer의 뉴런의 개수는 class의 개수와 같아야 한다.

pred_sum = tf.reshape(tf.reduce_sum(predictions,axis=1),(-1,1))
predictions = predictions / pred_sum

labels = tf.random.uniform(shape=(batch_size,),minval=0, maxval=n_class,dtype=tf.int32)

labels = tf.one_hot(labels,n_class)
print(labels)  # 이런 식으로 one hot값으로 나올 때는 CategoricalCrossentropy 사용

loss_object = CategoricalCrossentropy()

loss = loss_object(labels, predictions)


print("CategoricalCrossentropy(Tensorflow): ",loss.numpy())

tmp = tf.reduce_mean(tf.reduce_sum(-labels*tf.math.log(predictions),axis=1))

print("CategoricalCrossentropy(Manual): ",tmp.numpy())

tf.Tensor(
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]], shape=(16, 5), dtype=float32)
CategoricalCrossentropy(Tensorflow):  1.4612103
CategoricalCrossentropy(Manual):  1.4612103


CCE with Model/Dataset

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import CategoricalCrossentropy

N,n_feature = 8,2
n_class = 5

X = tf.zeros(shape = (0,n_feature))
Y = tf.zeros(shape=(0,),dtype = tf.int32)

for class_idx in range(n_class):
  center = tf.random.uniform(minval =-15, maxval=15, shape=(2,)) 

  x1 = center[0] + tf.random.normal(shape=(N,1)) 
  x2 = center[1] + tf.random.normal(shape=(N,1)) 

  x = tf.concat((x1,x2),axis=1)
  y = class_idx*tf.ones(shape=(N,), dtype=tf.int32)

  X = tf.concat((X,x), axis = 0)
  Y = tf.concat((Y,y), axis = 0)

Y = tf.one_hot(Y, depth=n_class,dtype=tf.int32) # one_hot 인코딩

dataset = tf.data.Dataset.from_tensor_slices((X,Y))
dataset = dataset.batch(batch_size)

model = Dense(units=n_class, activation='softmax')
loss_object = CategoricalCrossentropy()

for x,y in dataset:
  predictions = model(x)
  loss = loss_object(y,predictions)
  print(loss.numpy())

7.972014
4.4569654
0.22067007
