Shapes of Conv Layers

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28 , 28 , 1 
# 4차원 input
# 몇장, 높이, 넓이, 몇채널(R,G,B 같은것) -> 채널은 몇장이 겹쳐있냐고 생각하면 좋다.

n_filter = 1
k_size = 3 
# 커널 size 가 window size랑 같아야 한다는 것 생각하자

images = tf.random.uniform(minval=0, maxval=1, shape=((N,n_H,n_W,n_C)))


conv = Conv2D( filters =n_filter, kernel_size=k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(y.shape) # 28 - 3 + 1 = 26, 커널의 개수(필터 개수)가 1개 이기 때문에 이미지는 1장만 나오게 된다.
# 필터를 Dense의 뉴런처럼 생각하면 이해하기 좋다.
print(W.shape)
print(B.shape)

(1, 28, 28, 1)
(1, 26, 26, 1)
(3, 3, 1, 1)
(1,)


Correlation Calculation

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5 , 5 , 1 

n_filter = 1
k_size = 3 

images = tf.random.uniform(minval=0, maxval=1, shape=((N,n_H,n_W,n_C)))


conv = Conv2D( filters =n_filter, kernel_size=k_size)

y = conv(images)
print('Y(Tensorflow): \n',y.numpy().squeeze()) # 쓸데없는 1짜리 dimension을 없애주는 squeeze 라는 메소드
# 즉, 여기서는 몇장인지 몇겹인지가 안보이게 된다.
W, B = conv.get_weights()


images = images.numpy().squeeze()
W= W.squeeze()

y_man = np.zeros(shape=(n_H-k_size+1, n_W-k_size+1))
for i in range(n_H-k_size+1):
  for j in range(n_W-k_size+1):
    Window = images[i:i+k_size, j:j+k_size] # k_size 즉 window size만큼 나뉘어 지고,
    y_man[i,j] = np.sum(Window*W)+B # 그 window와 Weight를 correlation 시키고 Bias를 더하고

print("Y(Manual) : \n",y_man)



Y(Tensorflow): 
 [[ 0.27606472  0.28212565  0.4735132 ]
 [ 0.27920434 -0.0062186   0.13499665]
 [ 0.38137043  0.7240492   0.9987487 ]]
Y(Manual) : 
 [[ 0.27606472  0.28212565  0.47351319]
 [ 0.27920434 -0.0062186   0.13499665]
 [ 0.38137043  0.72404921  0.99874872]]


Correlation with n-channel

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5 , 5 , 3 

n_filter = 1
k_size = 3 

images = tf.random.uniform(minval=0, maxval=1, shape=((N,n_H,n_W,n_C)))


conv = Conv2D( filters =n_filter, kernel_size=k_size)

y = conv(images)
print('Y(Tensorflow): \n',y.numpy().squeeze()) 
W, B = conv.get_weights()


images = images.numpy().squeeze()
W= W.squeeze()

y_man = np.zeros(shape=(n_H-k_size+1, n_W-k_size+1))
for i in range(n_H-k_size+1):
  for j in range(n_W-k_size+1):
    Window = images[i:i+k_size, j:j+k_size, :] # Channel 이 생기면서 3차원이 되므로 : 추가 해줘야함
    y_man[i,j] = np.sum(Window*W)+B # 차원에 맞춰서 np.sum에서 correlation 해줌

print("Y(Manual) : \n",y_man)



Y(Tensorflow): 
 [[-1.3987637  -1.1099812  -1.1378502 ]
 [-1.2972409  -0.9867747  -1.4458784 ]
 [-1.027247   -0.50466377 -1.2553589 ]]
Y(Manual) : 
 [[-1.39876366 -1.10998118 -1.13785017]
 [-1.29724073 -0.98677468 -1.44587803]
 [-1.02724695 -0.50466371 -1.25535893]]
