Shapes with Filters

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N,n_H,n_W,n_C = 32,28,28,3
n_filter = 5
k_size = 3

images = tf.random.uniform(shape=(N,n_H,n_W,n_C),minval=0, maxval=1)

conv = Conv2D(filters = n_filter, kernel_size = k_size)

Y = conv(images)

W,B = conv.get_weights()

print("Input Images: {}".format(images.shape))
print("W/B: {} / {}".format(W.shape,B.shape))
print("Output Images: {}".format(Y.shape))

Input Images: (1, 28, 28, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Images: (1, 26, 26, 5)


Computation with Filters

In [24]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N,n_H,n_W,n_C = 1,5,5,3
n_filter = 3
k_size = 4

# Forward Propagation(Tensorflow)
images = tf.random.uniform(shape=(N,n_H,n_W,n_C),minval=0, maxval=1)

conv = Conv2D(filters = n_filter, kernel_size = k_size)

Y = conv(images)
print("Y(Tensorflow) : \n",Y.numpy()) # 1 2 2 3 shape이면 2,3 shape 2개가 1장있는 것
# tensor를 볼 줄 아는 능력이 매우 중요하다.

print(Y.numpy().squeeze().swapaxes(0,-1).shape) # 인덱스에서 -1은 제일 끝을 뜻하니까
# 제일 마지막 shape과 제일 앞 shape을 바꿔라 라는 뜻이 된다.
Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print("Y(Tensorflow) : \n",Y)

W,B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()
# print(W.shape, B.shape)

Y_man = np.zeros(shape=(n_H-k_size +1, n_W-k_size+1, n_filter))

for c in range(n_filter):
  c_w = W[:,:,:,c]
  c_b = B[c]

  print(c_w.shape, c_b.shape)
  for h in range(n_H-k_size +1):
    for j in range(n_W-k_size+1):
      window = images[h:h+k_size, j:j+k_size,:]
      conv = np.sum(window*c_w) +c_b

      Y_man[h,j,c] = conv

print("\n",Y_man.shape,"\n")
print("Y(Manual) : \n",np.transpose(Y_man,(2,0,1)))
print("Y(Manual) : \n",Y_man)


Y(Tensorflow) : 
 [[[[ 0.6982562  -0.22039403 -0.8788316 ]
   [ 1.0264459   0.13683249 -0.39404282]]

  [[ 1.2092285  -0.33673382 -0.46772408]
   [ 0.92333704  0.22510928 -0.14029597]]]]
(3, 2, 2)
Y(Tensorflow) : 
 [[[ 0.6982562   1.0264459 ]
  [ 1.2092285   0.92333704]]

 [[-0.22039403  0.13683249]
  [-0.33673382  0.22510928]]

 [[-0.8788316  -0.39404282]
  [-0.46772408 -0.14029597]]]
(4, 4, 3) ()
(4, 4, 3) ()
(4, 4, 3) ()

 (2, 2, 3) 

Y(Manual) : 
 [[[ 0.69825625  1.0264461 ]
  [ 1.20922828  0.92333704]]

 [[-0.22039399  0.13683243]
  [-0.33673376  0.22510928]]

 [[-0.87883168 -0.39404294]
  [-0.46772406 -0.14029604]]]
Y(Manual) : 
 [[[ 0.69825625 -0.22039399 -0.87883168]
  [ 1.0264461   0.13683243 -0.39404294]]

 [[ 1.20922828 -0.33673376 -0.46772406]
  [ 0.92333704  0.22510928 -0.14029604]]]


In [15]:
import numpy as np

images = np.random.randint(low=0, high=10, size=(2,3,4))

print(images,"\n\n")
for c in range(4):
  print(images[:,:,c],"\n") # 이게 실제로 우리가 생각하는 image tensor

images = np.transpose(images,(2,0,1)) 
# 여기서 2 0 1 은 처음 images shape을 봤을때 size =(2,3,4)이다.
# 2는 1차원 3은 2차원 4는 3차원을 뜻하니까 각각에서 -1을 한 2 0 1 을 사용한다
# 즉 2 0 1 은 3차원 부분을 맨 앞에, 1차원을 가운데, 2차원을 맨 뒤에 shape으로 바꿔라 라는 뜻이다
# 이렇게 바꾸게 되면 위에서 볼 수있듯이 우리가 보기에 좀더 편한 tensor 모습이 된다.

print(images.shape,"\n") # shape이 4 2 3으로 바뀐것을 볼 수 있다.

for c in range(4):
  print(images[c,:,:],"\n")

[[[3 9 1 4]
  [5 7 7 5]
  [3 3 7 1]]

 [[5 3 2 5]
  [7 5 2 8]
  [8 7 8 4]]] 


[[3 5 3]
 [5 7 8]] 

[[9 7 3]
 [3 5 7]] 

[[1 7 7]
 [2 2 8]] 

[[4 5 1]
 [5 8 4]] 

(4, 2, 3) 

[[3 5 3]
 [5 7 8]] 

[[9 7 3]
 [3 5 7]] 

[[1 7 7]
 [2 2 8]] 

[[4 5 1]
 [5 8 4]] 



Conv Layers with Activation Function

In [26]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N,n_H,n_W,n_C = 1,5,5,3
n_filter = 3
k_size = 4

# Forward Propagation(Tensorflow)
images = tf.random.uniform(shape=(N,n_H,n_W,n_C),minval=0, maxval=1)

conv = Conv2D(filters = n_filter, kernel_size = k_size,activation ='sigmoid')

Y = conv(images)
print("Y(Tensorflow) : \n",Y.numpy())

#print(Y.numpy().squeeze().swapaxes(0,-1).shape)
Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print("Y(Tensorflow) : \n",Y)

W,B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()


Y_man = np.zeros(shape=(n_H-k_size +1, n_W-k_size+1, n_filter))

for c in range(n_filter):
  c_w = W[:,:,:,c]
  c_b = B[c]

  print(c_w.shape, c_b.shape)
  for h in range(n_H-k_size +1):
    for j in range(n_W-k_size+1):
      window = images[h:h+k_size, j:j+k_size,:]
      conv = np.sum(window*c_w) +c_b
      conv = 1/(1+np.exp(-conv))
      Y_man[h,j,c] = conv

print("Y(Manual) : \n",np.transpose(Y_man,(2,0,1)))
print("Y(Manual) : \n",Y_man)


Y(Tensorflow) : 
 [[[[0.55420196 0.45735276 0.45510685]
   [0.3865586  0.45245    0.4373793 ]]

  [[0.5138548  0.46668285 0.46203744]
   [0.49782816 0.57451755 0.43860427]]]]
Y(Tensorflow) : 
 [[[0.55420196 0.3865586 ]
  [0.5138548  0.49782816]]

 [[0.45735276 0.45245   ]
  [0.46668285 0.57451755]]

 [[0.45510685 0.4373793 ]
  [0.46203744 0.43860427]]]
(4, 4, 3) ()
(4, 4, 3) ()
(4, 4, 3) ()
Y(Manual) : 
 [[[0.55420195 0.38655856]
  [0.51385476 0.49782818]]

 [[0.45735276 0.45245   ]
  [0.46668286 0.57451759]]

 [[0.45510686 0.43737931]
  [0.46203744 0.43860427]]]
Y(Manual) : 
 [[[0.55420195 0.45735276 0.45510686]
  [0.38655856 0.45245    0.43737931]]

 [[0.51385476 0.46668286 0.46203744]
  [0.49782818 0.57451759 0.43860427]]]
