3D Max Pooling

In [8]:
import math
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N,n_H,n_W,n_C =1,5,5,3
f,s = 2,2

x= tf.random.normal(shape = (N, n_H,n_W,n_C))
print("x:{}\n{}\n\n".format(x.shape,np.transpose(x.numpy().squeeze(),(2,0,1))))

pool_max = MaxPooling2D(pool_size= f, strides=s)
pooled_max = pool_max(x)
pooled_max_t = np.transpose(pooled_max.numpy().squeeze(),(2,0,1))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,pooled_max_t))

x = x.numpy().squeeze()
n_H_ = (n_H-f)/s + 1
n_W_ = (n_W-f)/s + 1
n_H_ = math.floor(n_H_) # floor 버림 사용하는 이유는 가우스 대신
n_W_ = math.floor(n_W_)

pooled_max_man = np.zeros(shape=(n_H_,n_W_,n_C))

for c in range(n_C):
  c_image = x[:,:,c] # 채널별로 들어오게 한다.

  h_ =0
  for h in  range(0,n_H-f+1, s):
    # strides가 사용되었기 때문에 for문에서도 s만큼씩 띄어서 생각해야함 
    w_ = 0
    for w in range(0,n_W-f+1, s):
      window = c_image[h:h+f,w:w+f]
      pooled_max_man[h_,w_,c] = np.max(window)

      w_+=1
    h_+=1
    # h_, w_ 가 쓰이는 이유는 strides 때문에 window는 (0,0), (0,2), (0,4) 이런식으로
    # 뽑히게 되는데 output에는 (0,0), (0,1), (0,2) 이런식으로 값이 저장되어야 하기 때문에
    # 새로운 변수를 사용한다.

pooled_max_t = np.transpose(pooled_max_man,(2,0,1))
print("pooled_max(Manual) : {}\n{}".format(pooled_max_man.shape,pooled_max_t))

x:(1, 5, 5, 3)
[[[-1.0502676   1.2770982   0.03033404  0.7994895  -0.68586665]
  [-0.21004531  0.23316449 -2.4170327   0.1353      0.97690994]
  [-1.2539772   0.84725523 -0.45474216  0.83537143  0.85136837]
  [-0.0194456  -1.9516449  -0.13189809 -1.4920213   1.4024311 ]
  [ 0.12080825  0.15417281 -1.9112555  -0.03213064  0.2915972 ]]

 [[-0.5239959   1.6991891  -0.96797425 -0.4085148   0.34251624]
  [-1.9530315  -0.27445933  0.9207175  -0.81990594 -0.02540627]
  [-0.8764721  -0.13476269  1.0693599   0.78142744  0.49529317]
  [-0.03037429 -0.00943185 -1.0276674  -0.04842126  1.5352051 ]
  [-2.2108836  -0.7447333   0.67215407 -0.8256411   2.019749  ]]

 [[ 0.5191984   0.05157617  0.22116666  0.7206553   0.39735198]
  [ 0.93230593  1.0184425  -0.47100732 -0.80700344 -0.87006724]
  [-0.46234825 -0.12444941 -1.4694221  -2.1948888   0.6539985 ]
  [ 1.0509129  -1.16504     0.883642   -0.26379132  0.816001  ]
  [ 1.7147588  -1.3303858  -0.09947148 -0.8240667  -0.5394334 ]]]


pooled_max(Tensor

Zero Padding2D Layer

In [16]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape = (1,3,3,3))
print(np.transpose(images.numpy().squeeze(),(2,0,1)))
print(images.shape)
zero_padding = ZeroPadding2D(padding=1) # '0'을 주변에 한칸 채우기
y= zero_padding(images)

print("\n\n",np.transpose(y.numpy().squeeze(),(2,0,1)))
print(y.shape)


[[[-0.3846912   0.59234536 -0.46360686]
  [ 0.10525272  0.09319694 -0.08259759]
  [ 0.56198275  1.0046477   2.217832  ]]

 [[ 0.52859145 -1.7081909   0.9380647 ]
  [-0.31842768 -1.0372095   0.23745482]
  [-0.320393    0.21897717  0.64425457]]

 [[ 0.8847934  -0.79589087  0.8353858 ]
  [-0.5795145  -0.20723662  1.2200066 ]
  [ 1.629732    1.8123257   0.9661668 ]]]
(1, 3, 3, 3)


 [[[ 0.          0.          0.          0.          0.        ]
  [ 0.         -0.3846912   0.59234536 -0.46360686  0.        ]
  [ 0.          0.10525272  0.09319694 -0.08259759  0.        ]
  [ 0.          0.56198275  1.0046477   2.217832    0.        ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.          0.        ]
  [ 0.          0.52859145 -1.7081909   0.9380647   0.        ]
  [ 0.         -0.31842768 -1.0372095   0.23745482  0.        ]
  [ 0.         -0.320393    0.21897717  0.64425457  0.        ]
  [ 0.          0.          0.          

Zero Padding with Conv2D Layers

In [17]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1,28,28,3))
conv = Conv2D(filters =1, kernel_size=3, padding='same') 
# conv layer에도 padding을 사용이 가능하다.
# 그런데 ZeroPadding2D를 사용하는 이유는 padding을 원하는 숫자로 명시적으로 사용하고 싶기 때문이다.
# padding = 'valid'는 padding을 사용 안한다는 소리이고, padding='same' 은 padding을 사용한다는 것이다.
# same일때 padding size는 input의 shape이 변하지 않도록 자동으로 맞춰진다.

y = conv(images)
print(y.shape) # y의 shape이 28 그대로 유지되는것을 볼 수 있는데, 이게 padding의 장점이다
# in과 out 사이의 shape이 유지되는


(1, 28, 28, 1)


Strides in Conv2D Layers

In [19]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1,28,28,3))
conv = Conv2D(filters =1, kernel_size=3, padding='valid', strides = 2)
y=conv(images)


print(images.shape)
print(y.shape) # strides가 2칸씩 띄어서 window를 만들기 때문에 이러한 결과가 나온다
# 그리고 conv 이기 때문에 channel이 1로 줄어들게 된다..

(1, 28, 28, 3)
(1, 13, 13, 1)


Strides in Pooling Layers

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape = (1,28,28,3))
pool = MaxPooling2D(pool_size=3, strides = 2)
y=pool(images)


print(images.shape)
print(y.shape)#  pooling 이기 때문에 channel이 유지된다.

(1, 28, 28, 3)
(1, 13, 13, 3)
