<a href="https://colab.research.google.com/github/SungHunYang/AI_start/blob/main/Affine_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Affine Function

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x=tf.constant([[10.]]) # input setting (Note : input -> matrix)
print(x)

dense = Dense(units=1, activation='linear') # imp.an affine function #affine function을 가져온 것
# units 는 affine function을 몇개 만들지 정하는 것이고,
# activation을 linear 로 하면 z 자체가 결과값이 되는것

y_tf = dense(x) # output # forward propagation + params initialization
print(y_tf)
# 여기를 통과 해야 즉, dense를 만나야 W, B를 초기화 된다.

W, B= dense.get_weights() # get weight, bias
print(W,B)

y_man  = tf.linalg.matmul(x, W) + B # forward propagation(manual)
# 여기는 직접 x값과 Weight를 넣고 +B까지 해서 식을 만든 것이다.


#print results
print("===== Input/ Weight/ Bias ======")
print("x: {} \n {} \n".format(x.shape,x.numpy()))
print("W: {} \n {} \n".format(W.shape,W))
print("B: {} \n {} \n".format(B.shape,B))

print("===== output/ Weight/ Bias ======")
print("y(tensorflow): {} \n {} \n".format(y_tf.shape,y_tf.numpy()))
print("y(manual): {} \n {} \n".format(y_man.shape,y_man.numpy()))
# tensorflow로 자동 계산 된것과 직접 식을 만들어 본것을 확인해보는 과정

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tf.Tensor([[-0.77956915]], shape=(1, 1), dtype=float32)
[[-0.07795691]] [0.]
===== Input/ Weight/ Bias ======
x: (1, 1) 
 [[10.]] 

W: (1, 1) 
 [[-0.07795691]] 

B: (1,) 
 [0.] 

===== output/ Weight/ Bias ======
y(tensorflow): (1, 1) 
 [[-0.77956915]] 

y(manual): (1, 1) 
 [[-0.77956915]] 



Params Initialization

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant


x=tf.constant([[10.]]) # input setting (Note : input -> matrix)

# weight/bias setting

w,b = tf.constant(10.), tf.constant(20.) 
# weight와 bias가 각각 상수 10 과 20으로 만들어주는 object가 되는거다
# 한마디로 지금 w,b를 출력하면 10 20 이 아니라 object 형태인 것이고,
# 이 object가 Dense나 layer를 만나면 상수화 되는 것
# 여기서 .은 floating point 32bit이기 때문에 적어준다.

w_init, b_init = Constant(w), Constant(b)

print(w_init, b_init)

# imp. an affine function
# weight, bias 초기화 시키기
dense = Dense(units=1, activation = 'linear', kernel_initializer = w_init,bias_initializer = b_init)
# kernel_intializer = w_init,bias_intializer = b_init 이전에 초기화 했던 것과는 다르게
# kernel_intializer = w_init,bias_intializer = b_init 를 통해서 내가 원하는 값으로 초기화

y_tf = dense(x)
print(y_tf) # input x =10, weight =10 bias =20 
# 즉 10X10+20 = 120 
W,B = dense.get_weights()

#print results
print("W : {} \n {}\n".format(W.shape,W))
print("B : {} \n {}\n".format(B.shape,B))

<keras.initializers.initializers_v2.Constant object at 0x7faa3bedcc50> <keras.initializers.initializers_v2.Constant object at 0x7faa3bedc7d0>
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W : (1, 1) 
 [[10.]]

B : (1,) 
 [20.]



Affine Function with n Features

In [16]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x=tf.random.uniform(shape=(1,10), minval=0, maxval=10)
# 1행 10열의 형태로 최소 0 ~ 최대 10 사이에서 uniform하게 만들어라
# row vector 1개의 값이 10개이다.
print(x.shape,'\n',x)

dense = Dense(units=1) # dense라는 affine Function을 만든것
# 인공지능 뉴런의 기본에서 affine function + activation function 이니까
# affine function을 만든 상태이고 activation은 linear로 default 되어 있는 상태인 것

y_tf = dense(x) # 여기서 보면 x를 input으로 넣은 거니까
# x의 개수 10개 만큼 자동으로 weight 10개 초기화

W, B = dense.get_weights() # weight는 컬럼 vector, bias는 scalar

y_man = tf.linalg.matmul(x, W) + B # = Z 를 말한다.

#print results
print("===== Input/ Weight/ Bias ======")
print("x: {} \n {} \n".format(x.shape,x.numpy()))
print("W: {} \n {} \n".format(W.shape,W))
print("B: {} \n {} \n".format(B.shape,B))

print("===== output/ Weight/ Bias ======")
print("y(tensorflow): {} \n {} \n".format(y_tf.shape,y_tf.numpy()))
print("y(manual): {} \n {} \n".format(y_man.shape,y_man.numpy()))

(1, 10) 
 tf.Tensor(
[[7.7889132  0.98971486 3.4335387  0.33073068 6.068529   6.867788
  2.8193164  3.7097073  6.8079996  8.706998  ]], shape=(1, 10), dtype=float32)
===== Input/ Weight/ Bias ======
x: (1, 10) 
 [[7.7889132  0.98971486 3.4335387  0.33073068 6.068529   6.867788
  2.8193164  3.7097073  6.8079996  8.706998  ]] 

W: (10, 1) 
 [[ 0.11251384]
 [ 0.7159937 ]
 [ 0.3837133 ]
 [ 0.4140424 ]
 [-0.5192524 ]
 [-0.60033673]
 [-0.529286  ]
 [-0.138327  ]
 [ 0.08178371]
 [ 0.44795984]] 

B: (1,) 
 [0.] 

===== output/ Weight/ Bias ======
y(tensorflow): (1, 1) 
 [[-1.7828708]] 

y(manual): (1, 1) 
 [[-1.7828708]] 

