Shapes of Dense Layers

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 1,10 # N은 데이터 사이즈 n_feature는 한개의 input 데이터 사이즈

X = tf.random.normal(shape =(N,n_feature))

n_neuron = 3
dense = Dense(units = n_neuron , activation = 'sigmoid') 
'''
이게 하나의 layer를 뜻한다
그리고 여기서 units이 바로 뉴런의 개수를 말한다.
'''

Y= dense(X) # 3개의 뉴런을 가진 layer에 input을 넣은 것

W, B = dense.get_weights()

print("======= INPUT/ WEIGHT/ BIAS =======")
print("X : ",X.shape) #(1,10)
print("W : ",W.shape) #(10,3)
print("B : ",B.shape) #(3.)
print("Y : ",Y.shape) #(1,3)
print(W)

======= INPUT/ WEIGHT/ BIAS =======
X :  (1, 10)
W :  (10, 3)
B :  (3,)
Y :  (1, 3)
[[ 0.24157119  0.636752   -0.03452337]
 [ 0.31373703  0.20599067  0.17645478]
 [-0.63622653 -0.37487397  0.2721359 ]
 [-0.14584243  0.0791952  -0.6337132 ]
 [-0.28767973 -0.42576623 -0.6431734 ]
 [ 0.52565753 -0.45815462  0.6154754 ]
 [ 0.6759063   0.52188337  0.46381557]
 [-0.19645739 -0.2774129   0.11529922]
 [-0.43560576  0.18241328  0.5904374 ]
 [-0.02684194  0.24793047  0.05805814]]


Output Calculations

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.math import exp # e 
from tensorflow.linalg import matmul # 행렬 곱
from tensorflow.keras.layers import Dense

N, n_feature = 4,10 # N은 데이터 사이즈 n_feature는 한개의 input 데이터 사이즈

X = tf.random.normal(shape =(N,n_feature))

n_neuron = 3
dense = Dense(units = n_neuron , activation = 'sigmoid') 
'''
이게 하나의 layer를 뜻한다
그리고 여기서 units이 바로 뉴런의 개수를 말한다.
'''

Y_tf= dense(X) # 3개의 뉴런을 가진 layer에 input을 넣은 것

W, B = dense.get_weights() 
'''
궁금증. dense에서 W,B는 랜덤으로 정해지고 있는 상태인것인가?
'''

print("Y(Tensorflow) : \n",Y_tf.numpy())

# calculate with matrix multiplication

z = matmul(X,W) +B
Y_man_matmul = 1/(1+exp(-z))
print("Y_man_matmul : \n",Y_man_matmul.numpy())

# calculate with dot products

Y_man_vec = np.zeros(shape =(N,n_neuron))
for x_idx in range(N):
  x = X[x_idx] # 이렇게 하면 넘파이에서 한 행씩 뽑아 옴

  for nu_idx in range(n_neuron):
    w,b = W[:,nu_idx], B[nu_idx]

    z = tf.reduce_sum(x*w) + b
    a= 1/(1+np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot product) : \n",Y_man_vec)


Y(Tensorflow) : 
 [[0.4603909  0.9201728  0.30001208]
 [0.6061809  0.90450925 0.5575744 ]
 [0.6542806  0.75549036 0.1996417 ]
 [0.48402804 0.48103762 0.5548951 ]]
Y_man_matmul : 
 [[0.46039093 0.9201728  0.30001208]
 [0.6061809  0.90450925 0.5575744 ]
 [0.6542806  0.7554903  0.1996417 ]
 [0.484028   0.48103768 0.5548951 ]]
Y(with dot product) : 
 [[0.46039089 0.92017283 0.30001209]
 [0.6061809  0.90450923 0.55757439]
 [0.65428062 0.75549034 0.1996417 ]
 [0.48402806 0.48103764 0.55489511]]


Shapes of Cacaded Dense Layers

In [22]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape =(N,n_feature))

n_neurons = [3,5] # 이런 식으로 되면 dense layer를 만들 수 있다.
# n_neurons[0] = 3 이고, n_neurons[1] = 5

dense1 = Dense(units = n_neurons[0], activation = 'sigmoid') # 3개의 뉴런 
dense2 = Dense(units = n_neurons[1], activation = 'sigmoid') # 5개의 뉴런

# forward propagation
A1 = dense1(X)
Y = dense2(A1) # 이런 식으로 dense layer는 이전 layer의 결과 값이 input으로 들어간다.

print("X : {}\n".format(X.shape)) # 4,10
print("A1 : {}\n".format(A1.shape)) # 4,3
print("Y : {}\n".format(Y.shape)) #4,5

# get weight/bias

W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()
print("W1 : ",W1.shape)
print("B1 : ",B1.shape)
print("W2 : ",W2.shape)
print("B2 : ",B2.shape)

X : (4, 10)

A1 : (4, 3)

Y : (4, 5)

W1 :  (10, 3)
B1 :  (3,)
W2 :  (3, 5)
B2 :  (5,)


Dense Layers with Python List

In [25]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape =(N,n_feature))

n_neurons = [10,20,30,40,50,60,70,80,90,100]

dense_layers = list() # 리스트 형식으로 여러개의 layer를 만드는 것

for n_neuron in n_neurons: # 여러개의 layer 생성
  dense = Dense(units = n_neuron, activation = 'relu')
  dense_layers.append(dense)

print("Input: ",X.shape)
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X) 
  '''
  여기 코드는 이전의 X값 input이 dense에 들어가서 X 라는 또 다른 output이 되고
  그 output이 input으로 들어가는 형태이다. 즉, dense_layer 방식과 같다.
  '''
  print("After dense layer",dense_idx) # 열거형이기 때문에 idx 존재
  print(X.shape,'\n')

Y = x # output Y를 구함

Input:  (4, 10)
After dense layer 0
(4, 10) 

After dense layer 1
(4, 20) 

After dense layer 2
(4, 30) 

After dense layer 3
(4, 40) 

After dense layer 4
(4, 50) 

After dense layer 5
(4, 60) 

After dense layer 6
(4, 70) 

After dense layer 7
(4, 80) 

After dense layer 8
(4, 90) 

After dense layer 9
(4, 100) 



Output Calculation

In [31]:
import tensorflow as tf
from tensorflow.math import exp 
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape =(N,n_feature))
X_cp = tf.identity(x) 
# 이걸 만일 X_cp = X 라고 하면 주소값을 복사하기 때문에 같이 바뀌어서 의미 X
# 따라서 identity를 통해서 값만 복사

n_neurons = [3,4,5]

dense_layers = list() # 리스트 형식으로 여러개의 layer를 만드는 것

# forward propagation(Tensorflow)
for n_neuron in n_neurons: # 여러개의 layer 생성
  dense = Dense(units = n_neuron, activation = 'sigmoid')
  dense_layers.append(dense)

W,B = list(),list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X) 
  w,b = dense.get_weights()

  W.append(w)
  B.append(b)

print("Y(tensorflow) : \n",Y.numpy())

'''
# forward propagation(Manual)

for layer_idx in range(len(n_neurons)):
  w,b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1+exp(-X_cp))

print("Y(Manual) : \n",X_cp.numpy())
'''

Y(tensorflow) : 
 [[0.43465936 0.61384875 0.4862559  0.53122884 0.64410543]
 [0.48671758 0.5490625  0.51265454 0.56545085 0.5121069 ]
 [0.4735602  0.619158   0.6073555  0.5126441  0.40985644]
 [0.48510665 0.5428168  0.50586486 0.5477917  0.52346045]]


InvalidArgumentError: ignored